import Hero from "./hero";
import Title from "./title";
import Navbar from "./navbar";
import Middle from "./middle";
import Features from "./features";
import StepTracker from "./StepTracker";
import Footer from "./footer";
import FetchApi from "./fetchapi";
//import CustomButton from "./CustomButton";
export { Navbar, Title, Middle, Hero, Features, StepTracker, Footer, FetchApi };
